name: Deployment pipeline!

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: npm install 
        run: npm install  

      - name: lint
        run: npm run eslint 

      - name: test
        run: npm test

      - name: build
        run: npm run build   

      - name: pushing code to heroku #push code to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "full-stack-open-pokedex-cicd"
          heroku_email: "dato.ardzenadze.2000@gmail.com"
          healthcheck: "https://full-stack-open-pokedex-cicd.herokuapp.com/health" #healthchek
          checkstring: "ok"
          rollbackonhealthcheckfailed: true